/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.manager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business;
import model.Product;

/**
 *
 * @author grace
 */
public class ManagerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel mainWorkArea;  // ADD THIS
    private Business business;
    /**
     * Creates new form AddProductJPanel
     */
    public ManagerWorkAreaJPanel(JPanel mainWorkArea, Business business) {
        initComponents();
        this.mainWorkArea = mainWorkArea;  // ADD THIS
        this.business = business;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        menuBar = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        btnListOrders = new javax.swing.JButton();
        btnManageProduct = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();
        btnViewProduct = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuBar.setBackground(new java.awt.Color(153, 153, 153));

        lblWelcome.setText("<WelcomeMsg>");

        btnAddCustomer.setBackground(new java.awt.Color(0, 153, 153));
        btnAddCustomer.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnAddCustomer.setText("Add Customer + Order");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnListOrders.setBackground(new java.awt.Color(0, 153, 153));
        btnListOrders.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnListOrders.setText("List Orders");
        btnListOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListOrdersActionPerformed(evt);
            }
        });

        btnManageProduct.setBackground(new java.awt.Color(0, 153, 153));
        btnManageProduct.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnManageProduct.setText("Manage Products");
        btnManageProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProductActionPerformed(evt);
            }
        });

        btnSearchCustomer.setBackground(new java.awt.Color(0, 153, 153));
        btnSearchCustomer.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnSearchCustomer.setText("Search Customers");
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        btnViewProduct.setBackground(new java.awt.Color(0, 153, 153));
        btnViewProduct.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnViewProduct.setText("View Product");
        btnViewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(0, 255, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblWelcome)
                .addGap(50, 50, 50)
                .addComponent(btnAddCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnListOrders)
                .addGap(18, 18, 18)
                .addComponent(btnManageProduct)
                .addGap(18, 18, 18)
                .addComponent(btnSearchCustomer)
                .addGap(26, 26, 26)
                .addComponent(btnViewProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addGap(18, 18, 18))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(btnAddCustomer)
                    .addComponent(btnListOrders)
                    .addComponent(btnManageProduct)
                    .addComponent(btnSearchCustomer)
                    .addComponent(btnViewProduct)
                    .addComponent(btnHome))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(menuBar);

        workArea.setBackground(new java.awt.Color(0, 153, 153));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductActionPerformed
        // TODO add your handling code here:
        if (business.getProductCatalog().getProductList().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No products available to view", "Info", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // Create array of product names for selection
    Product[] products = business.getProductCatalog().getProductList().toArray(new Product[0]);
    
    Product selectedProduct = (Product) JOptionPane.showInputDialog(
        this,
        "Select a product to view:",
        "View Product",
        JOptionPane.QUESTION_MESSAGE,
        null,
        products,
        products[0]
    );
    
    if (selectedProduct != null) {
        ViewProductJPanel panel = new ViewProductJPanel(workArea, business, selectedProduct);
        workArea.add("ViewProduct", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }
    }//GEN-LAST:event_btnViewProductActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
         AddCustomerOrderJPanel panel = new AddCustomerOrderJPanel(workArea, business);
        workArea.add("AddCustomerOrder", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnManageProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProductActionPerformed
        // TODO add your handling code here:
        ManageProductJPanel panel = new ManageProductJPanel(workArea, business);
        workArea.add("ManageProduct", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageProductActionPerformed

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        // TODO add your handling code here:
        SearchCustomerJPanel panel = new SearchCustomerJPanel(workArea, business);
        workArea.add("SearchCustomer", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnListOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListOrdersActionPerformed
        // TODO add your handling code here:
        ListOrdersJPanel panel = new ListOrdersJPanel(workArea, business);
        workArea.add("ListOrders", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnListOrdersActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "Home");
    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListOrders;
    private javax.swing.JButton btnManageProduct;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnViewProduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel menuBar;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
