/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;
import model.Business;
import model.Customer;
import model.Product;

/**
 *
 * @author grace
 */
public class MainJFrame extends javax.swing.JFrame {
    private Business business;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
         initializeBusiness();
         setSize(800,600);
        setResizable(false);
        
        // Create and display home panel
        initializeHomePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainWorkArea.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(mainWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(mainWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    private void initializeBusiness() {
         business = new Business("Coffee Shop");
        
        // Add sample products (required by assignment - minimum 5)
        business.getProductCatalog().addProduct(101, "Espresso", "Coffee", 2.50, 50, 3);
        business.getProductCatalog().addProduct(102, "Latte", "Coffee", 4.00, 30, 5);
        business.getProductCatalog().addProduct(103, "Green Tea", "Tea", 2.00, 40, 4);
        business.getProductCatalog().addProduct(104, "Croissant", "Pastry", 3.50, 20, 2);
        business.getProductCatalog().addProduct(105, "Club Sandwich", "Sandwich", 7.50, 15, 8);
        
        // Add sample customers with same names for search testing (required by assignment)
        business.getOrderDirectory().addCustomer(1001, "John", "Smith", "555-0101");
        business.getOrderDirectory().addCustomer(1002, "John", "Doe", "555-0102");
        business.getOrderDirectory().addCustomer(1003, "Jane", "Smith", "555-0103");
        business.getOrderDirectory().addCustomer(1004, "Alice", "Johnson", "555-0104");
        business.getOrderDirectory().addCustomer(1005, "Bob", "Wilson", "555-0105");
        
        // Add sample orders (minimum 3 required by assignment)
        Customer customer1 = business.getOrderDirectory().searchCustomerById(1001);
        Customer customer2 = business.getOrderDirectory().searchCustomerById(1002);
        Customer customer3 = business.getOrderDirectory().searchCustomerById(1003);
        
        Product latte = business.getProductCatalog().searchProduct(102);
        Product espresso = business.getProductCatalog().searchProduct(101);
        Product sandwich = business.getProductCatalog().searchProduct(105);
        
        business.getOrderDirectory().addOrder(2001, new Date(), "Dine-in", "Cash", "Completed", latte, customer1, 1);
        business.getOrderDirectory().addOrder(2002, new Date(), "Takeout", "Card", "Ready", espresso, customer2, 2);
        business.getOrderDirectory().addOrder(2003, new Date(), "Pickup", "Mobile", "Preparing", sandwich, customer3, 1);
    }

    private void initializeHomePanel() {
        HomeJPanel homePanel = new HomeJPanel(mainWorkArea, business);
        mainWorkArea.add("Home", homePanel);
        
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "Home");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainWorkArea;
    // End of variables declaration//GEN-END:variables
}
