/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customer;

/**
 *
 * @author grace
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        customerMenuBar = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        WorkArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        splitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        lblWelcome.setText("<Welcome Msg>");

        btnOrder.setText("Order");

        btnView.setText("View");

        btnHistory.setText("History");

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerMenuBarLayout = new javax.swing.GroupLayout(customerMenuBar);
        customerMenuBar.setLayout(customerMenuBarLayout);
        customerMenuBarLayout.setHorizontalGroup(
            customerMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerMenuBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblWelcome)
                .addGap(61, 61, 61)
                .addComponent(btnOrder)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addGap(30, 30, 30)
                .addComponent(btnHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnHome)
                .addContainerGap())
        );
        customerMenuBarLayout.setVerticalGroup(
            customerMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerMenuBarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(customerMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(btnOrder)
                    .addComponent(btnView)
                    .addComponent(btnHistory)
                    .addComponent(btnHome))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        splitPanel.setTopComponent(customerMenuBar);

        WorkArea.setLayout(new java.awt.CardLayout());
        splitPanel.setRightComponent(WorkArea);

        add(splitPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WorkArea;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel customerMenuBar;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JSplitPane splitPanel;
    // End of variables declaration//GEN-END:variables
}
